<?php
/**
 * The base configuration for WordPress
 * Standard Root Install - David Hyland 2026 Refactor
 */

// 1. SET ENVIRONMENT CONSTANT (Used by themes and config loader)
if ( isset($_SERVER['HTTP_HOST']) && strpos($_SERVER['HTTP_HOST'], '.test') !== false ) {
    define( 'ENV', 'local' );
} elseif ( isset($_SERVER['HTTP_HOST']) && strpos($_SERVER['HTTP_HOST'], 'staging.') !== false ) {
    define( 'ENV', 'staging' );
} else {
    define( 'ENV', 'production' );
}

// 2. LOAD ENVIRONMENT CONFIG
// This pulls from your /config/ folder generated by setup.sh
$config_file = __DIR__ . '/config/' . ENV . '-config.php';

if ( file_exists( $config_file ) ) {
    include_once $config_file;
}

// 3. DATABASE DEFAULTS (Overridden by local-config.php if present)
if ( ! defined( 'DB_CHARSET' ) ) {
    define( 'DB_CHARSET', 'utf8mb4' );
}
if ( ! defined( 'DB_COLLATE' ) ) {
    define( 'DB_COLLATE', '' );
}

/**
 * Absolute path to the WordPress directory.
 * In a standard install, this is the current directory.
 */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';